/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//-------------------------------------------------------------------------
// Function declarations

class AppleHPET : IOACPIPlatformDevice
{
    OSDeclareDefaultStructors(AppleHPET)

public:
    virtual uint8_t start(AppleHPET *owner = this, IOService *a2);
    virtual uint8_t probeHPET(AppleHPET *owner = this);
    virtual uint32_t configureTimer(AppleHPET *owner = this, void *a2);
    virtual uint8_t cpuDriverPublished(void *a1, void *a2, void *a3, void *a4);
    virtual IOReturn stop(AppleHPET *owner = this, IOService *a2);
    virtual IOReturn free(AppleHPET *owner = this);
    virtual uint64_t hpetTimerAcquire(AppleHPET *owner = this, uint32_t, void (*)(void), uint32_t *, uint32_t *, void **);
    virtual IOReturn hpetTimerRelease(AppleHPET *owner = this, uint32_t a2);
    virtual uint64_t hpetTimerCommand(AppleHPET *owner = this, uint32_t a2, int32_t a3);
    virtual uint64_t hpetSaveState(AppleHPET *owner = this);
    virtual uint64_t hpetRestoreState(AppleHPET *owner = this);
    virtual IOReturn setInterruptMessageDestination(AppleHPET *owner, void *data, uint32_t dataSize);
    virtual uint64_t getInterruptVectorAtIndex(AppleHPET *owner = this, uint32_t index);
    virtual IOReturn getInterruptControllerAtIndex(AppleHPET *this, uint32_t index);
};

// int __fastcall IOFree(_QWORD, _QWORD); weak
// int __cdecl IOLockAlloc(_QWORD); weak
// int __cdecl IOLockFree(_QWORD); weak
// int __fastcall IOLockLock(_QWORD); weak
// int __fastcall IOLockUnlock(_QWORD); weak
// int __fastcall IOLog(_QWORD); weak
// int __fastcall IOMalloc(_QWORD); weak
// int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD __cdecl OSMetaClass::~OSMetaClass(OSMetaClass *__hidden this); idb
// int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD); weak
// _QWORD __cdecl IOMemoryDescriptor::withAddressRange(IOMemoryDescriptor *__hidden this, unsigned __int64, unsigned __int64, unsigned int, task *); idb
// _QWORD __cdecl OSNumber::withNumber(OSNumber *__hidden this, unsigned __int64, unsigned int); idb
// void __cdecl OSObject::operator delete(void *); idb
// _QWORD __cdecl OSObject::operator new(OSObject *__hidden this, unsigned __int64); idb
// _QWORD IOService::getPlatform(IOService *__hidden this); idb
// int __fastcall IOService::serviceMatching(_QWORD, _QWORD); weak
// int __fastcall IOService::addMatchingNotification(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// int __cdecl IOService::IOService(_QWORD); weak
// _QWORD __cdecl IOService::~IOService(IOService *__hidden this); idb
// _QWORD OSMetaClass::instanceConstructed(OSMetaClass *__hidden this); idb
// int __fastcall kprintf(_QWORD); weak
// void *__cdecl memset(void *, int, size_t);
// int __fastcall pmCPUControl(_QWORD, _QWORD); weak
// size_t __cdecl strlen(const char *);
// int __cdecl strncmp(const char *, const char *, size_t);

//-------------------------------------------------------------------------
// Data declarations
section_64 stru_B8 =
{
  {
    '_',
    '_',
    'c',
    's',
    't',
    'r',
    'i',
    'n',
    'g',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0'
  },
  "__TEXT",
  7623uLL,
  535uLL,
  7623u,
  0u,
  0u,
  0u,
  2u,
  0u,
  0u,
  0u
}; // weak

Int64 AppleHPET::probeHPET(void)::ErrataTable[2] = {
  -217604518102508LL,
  -217587338233320LL
}; // weak

UInt64 off_2000[11] =
{
  41456LL,
  41464LL,
  41472LL,
  41640LL,
  41656LL,
  43232LL,
  43248LL,
  43256LL,
  43264LL,
  43272LL,
  43280LL
}; // weak

UInt64 off_2008[10] =
{
  41464LL,
  41472LL,
  41640LL,
  41656LL,
  43232LL,
  43248LL,
  43256LL,
  43264LL,
  43272LL,
  43280LL
}; // weak

UInt64 off_2010[9] =
{
  41472LL,
  41640LL,
  41656LL,
  43232LL,
  43248LL,
  43256LL,
  43264LL,
  43272LL,
  43280LL
}; // weak

_QWORD off_2018[8] = { 41640LL, 41656LL, 43232LL, 43248LL, 43256LL, 43264LL, 43272LL, 43280LL }; // weak
_QWORD off_2020[7] = { 41656LL, 43232LL, 43248LL, 43256LL, 43264LL, 43272LL, 43280LL }; // weak
__int64 off_2028[6] = { 43232LL, 43248LL, 43256LL, 43264LL, 43272LL, 43280LL }; // weak
__int64 off_2030[5] = { 43248LL, 43256LL, 43264LL, 43272LL, 43280LL }; // weak
__int64 off_2038[4] = { 43256LL, 43264LL, 43272LL, 43280LL }; // weak
__int64 off_2040[3] = { 43264LL, 43272LL, 43280LL }; // weak
__int64 off_2048[2] = { 43272LL, 43280LL }; // weak
__int64 off_2050 = 43280LL; // weak
__int64 (__fastcall *off_2090[2])(AppleHPET *__hidden this) = { &AppleHPET::~AppleHPET, &AppleHPET::~AppleHPET }; // weak
__int64 (__fastcall *off_2900[2])(AppleHPET::MetaClass *__hidden this) = { &AppleHPET::MetaClass::~MetaClass, &AppleHPET::MetaClass::~MetaClass }; // weak
__int64 kmod_info = 0LL; // weak
_QWORD AppleHPET::gMetaClass; // weak
int (*_realmain)(void); // weak
int (*_antimain)(void); // weak


//----- (0000000000000B90) ----------------------------------------------------
__int64 __fastcall AppleHPET::MetaClass::MetaClass(AppleHPET::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleHPET", off_2020[0], 248LL);
  result = (__int64)off_2900;
  *(_QWORD *)this = off_2900;
  return result;
}
// 2020: using guessed type _QWORD off_2020[7];
// 2900: using guessed type __int64 (__fastcall *off_2900[2])(AppleHPET::MetaClass *__hidden this);
// 9FE8: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000BC2) ----------------------------------------------------
__int64 __fastcall AppleHPET::MetaClass::~MetaClass(AppleHPET::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000000BCC) ----------------------------------------------------
__int64 __fastcall AppleHPET::AppleHPET(__int64 a1)
{
  __int64 result; // rax@1

  IOService::IOService(a1);
  result = (__int64)off_2090;
  *(_QWORD *)a1 = off_2090;
  return result;
}
// 2090: using guessed type __int64 (__fastcall *off_2090[2])(AppleHPET *__hidden this);
// A6D8: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (0000000000000BEC) ----------------------------------------------------
__int64 __fastcall AppleHPET::AppleHPET(__int64 a1)
{
  __int64 result; // rax@1

  IOService::IOService(a1);
  result = (__int64)off_2090;
  *(_QWORD *)a1 = off_2090;
  return result;
}
// 2090: using guessed type __int64 (__fastcall *off_2090[2])(AppleHPET *__hidden this);
// A6D8: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (0000000000000C0C) ----------------------------------------------------
__int64 __fastcall AppleHPET::~AppleHPET(AppleHPET *this)
{
  return IOService::~IOService(this);
}

//----- (0000000000000C16) ----------------------------------------------------
__int64 __fastcall AppleHPET::~AppleHPET(AppleHPET *this)
{
  return IOService::~IOService(this);
}

//----- (0000000000000C20) ----------------------------------------------------
void __fastcall AppleHPET::~AppleHPET(AppleHPET *this)
{
  IOService::~IOService(this);
  OSObject::operator delete((void *)this);
}

//----- (0000000000000C42) ----------------------------------------------------
__int64 __fastcall AppleHPET::getMetaClass(AppleHPET *this)
{
  return (__int64)&AppleHPET::gMetaClass;
}
// 2AA0: using guessed type _QWORD AppleHPET::gMetaClass;

//----- (0000000000000C50) ----------------------------------------------------
__int64 __fastcall AppleHPET::MetaClass::MetaClass(AppleHPET::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleHPET", off_2020[0], 248LL);
  result = (__int64)off_2900;
  *(_QWORD *)this = off_2900;
  return result;
}
// 2020: using guessed type _QWORD off_2020[7];
// 2900: using guessed type __int64 (__fastcall *off_2900[2])(AppleHPET::MetaClass *__hidden this);
// 9FE8: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000C82) ----------------------------------------------------
__int64 __fastcall AppleHPET::MetaClass::alloc(AppleHPET::MetaClass *this, unsigned __int64 a2)
{
  __int64 v2; // rbx@1

  v2 = OSObject::operator new((OSObject *)&stru_B8.flags, a2);
  IOService::IOService(v2);
  *(_QWORD *)v2 = off_2090;
  OSMetaClass::instanceConstructed((OSMetaClass *)&AppleHPET::gMetaClass);
  return v2;
}
// B8: using guessed type section_64;
// 2090: using guessed type __int64 (__fastcall *off_2090[2])(AppleHPET *__hidden this);
// 2AA0: using guessed type _QWORD AppleHPET::gMetaClass;
// A6D8: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (0000000000000CC2) ----------------------------------------------------
__int64 __fastcall AppleHPET::AppleHPET(__int64 a1)
{
  IOService::IOService(a1);
  *(_QWORD *)a1 = off_2090;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleHPET::gMetaClass);
}
// 2090: using guessed type __int64 (__fastcall *off_2090[2])(AppleHPET *__hidden this);
// 2AA0: using guessed type _QWORD AppleHPET::gMetaClass;
// A6D8: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (0000000000000CF2) ----------------------------------------------------
__int64 __fastcall AppleHPET::AppleHPET(__int64 a1)
{
  IOService::IOService(a1);
  *(_QWORD *)a1 = off_2090;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleHPET::gMetaClass);
}
// 2090: using guessed type __int64 (__fastcall *off_2090[2])(AppleHPET *__hidden this);
// 2AA0: using guessed type _QWORD AppleHPET::gMetaClass;
// A6D8: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (0000000000000D22) ----------------------------------------------------
char __fastcall AppleHPET::start(AppleHPET *this, IOService *a2)
{
  __int64 v2; // r12@1
  __int64 v3; // rax@2
  __int64 v4; // rax@3
  char *v5; // r13@3
  __int64 v6; // rax@5
  __int64 v7; // rax@6
  unsigned __int64 v8; // rax@7
  __int64 v9; // r15@10
  char result; // al@17
  __int64 v11; // rax@19
  __int64 v12; // rax@20
  unsigned int v13; // er15@21
  signed __int64 v14; // r13@21
  __int64 v15; // r12@22
  __int64 v16; // rax@25
  __int64 v17; // r15@25
  __int64 v18; // rax@26
  char *v19; // r12@26

  v2 = off_2028[0];
  if ( !(unsigned __int8)(*(int (__cdecl **)(AppleHPET *))(off_2028[0] + 1488))(this) )
    return 0;
  LODWORD(v3) = IOLockAlloc(this);
  *((_QWORD *)this + 22) = v3;
  if ( !v3 )
  {
    kprintf("HPET: IOLockAlloc() failed\n");
    IOLog("HPET: IOLockAlloc() failed\n");
    v5 = (char *)this + 136;
    goto LABEL_14;
  }
  LODWORD(v4) = OSMetaClassBase::safeMetaCast(a2, *(_QWORD *)off_2000[0]);
  v5 = (char *)this + 136;
  *((_QWORD *)this + 17) = v4;
  if ( !v4 )
  {
    v9 = (__int64)"HPET: provider is not an IOACPIPlatformDevice\n";
LABEL_13:
    kprintf(v9);
    IOLog(v9);
    goto LABEL_14;
  }
  if ( !(unsigned __int8)(*(int (__fastcall **)(__int64, AppleHPET *, _QWORD, _QWORD))(*(_QWORD *)v4 + 1488LL))(
                           v4,
                           this,
                           0LL,
                           0LL) )
  {
    v9 = (__int64)"HPET: device open failed\n";
    goto LABEL_13;
  }
  LODWORD(v6) = (*(int (__fastcall **)(_QWORD, _QWORD, signed __int64))(**((_QWORD **)this + 17) + 1760LL))(
                  *((_QWORD *)this + 17),
                  0LL,
                  256LL);
  *((_QWORD *)this + 18) = v6;
  if ( !v6 || (LODWORD(v7) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v6 + 280LL))(v6), !v7) )
  {
    v9 = (__int64)"HPET: map device registers failed\n";
    goto LABEL_13;
  }
  LODWORD(v8) = (*(int (__cdecl **)(_QWORD))(**((_QWORD **)this + 18) + 296LL))(*((_QWORD *)this + 18));
  if ( v8 <= 0x3FF )
  {
    kprintf("HPET: register space too small (min = %d)\n");
    IOLog("HPET: register space too small (min = %d)\n");
LABEL_14:
    if ( *(_QWORD *)v5 )
      (*(void (__fastcall **)(_QWORD, AppleHPET *, _QWORD))(**(_QWORD **)v5 + 1496LL))(*(_QWORD *)v5, this, 0LL);
    (*(void (__fastcall **)(AppleHPET *, IOService *))(v2 + 1496))(this, a2);
    return 0;
  }
  LODWORD(v11) = (*(int (__cdecl **)(_QWORD))(**((_QWORD **)this + 18) + 280LL))(*((_QWORD *)this + 18));
  *((_QWORD *)this + 24) = v11;
  if ( !AppleHPET::probeHPET(this) )
  {
    v9 = (__int64)"HPET: probeHPET() failed\n";
    goto LABEL_13;
  }
  LODWORD(v12) = IOMalloc(40LL * *((_DWORD *)this + 53));
  *((_QWORD *)this + 25) = v12;
  if ( !v12 )
  {
    v9 = (__int64)"HPET: No memory for timers\n";
    goto LABEL_13;
  }
  v13 = 0;
  v14 = 256LL;
  if ( *((_DWORD *)this + 53) )
  {
    v15 = 0LL;
    while ( 1 )
    {
      *(_QWORD *)(v12 + v15) = v14 + *((_QWORD *)this + 24);
      *(_DWORD *)(v12 + v15 + 8) = v13;
      *(_DWORD *)(v12 + v15 + 12) = -1;
      *(_DWORD *)(v12 + v15 + 16) = -1;
      *(_DWORD *)(v12 + v15 + 20) = 0;
      *(_QWORD *)(v12 + v15 + 24) = 0LL;
      *(_QWORD *)(v12 + v15 + 32) = 0LL;
      AppleHPET::configureTimer(this, v12 + v15);
      ++v13;
      if ( v13 >= *((_DWORD *)this + 53) )
        break;
      v12 = *((_QWORD *)this + 25);
      v15 += 40LL;
      v14 += 32LL;
    }
  }
  LODWORD(v16) = IOService::serviceMatching("AppleIntelCPUPowerManagement", 0LL);
  v17 = v16;
  v5 = (char *)this + 136;
  if ( v16 )
  {
    LODWORD(v18) = IOService::addMatchingNotification(
                     *(_QWORD *)off_2038[0],
                     v16,
                     AppleHPET::cpuDriverPublished,
                     this,
                     0LL,
                     0LL);
    v19 = (char *)this + 184;
    *((_QWORD *)this + 23) = v18;
    (*(void (__fastcall **)(__int64))(*(_QWORD *)v17 + 40LL))(v17);
  }
  else
  {
    v19 = (char *)this + 184;
  }
  result = 1;
  if ( !*(_QWORD *)v19 )
  {
    kprintf("HPET: No memory for notifier\n");
    IOLog("HPET: No memory for notifier\n");
    v2 = off_2028[0];
    goto LABEL_14;
  }
  return result;
}
// 2000: using guessed type _QWORD off_2000[11];
// 2028: using guessed type __int64 off_2028[6];
// 2038: using guessed type __int64 off_2038[4];
// 9F78: using guessed type int __cdecl IOLockAlloc(_QWORD);
// 9F98: using guessed type int __fastcall IOLog(_QWORD);
// 9FA0: using guessed type int __fastcall IOMalloc(_QWORD);
// A1B8: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);
// A3C0: using guessed type int __fastcall IOService::serviceMatching(_QWORD, _QWORD);
// A640: using guessed type int __fastcall IOService::addMatchingNotification(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// A918: using guessed type int __fastcall kprintf(_QWORD);

//----- (000000000000101E) ----------------------------------------------------
char __fastcall AppleHPET::probeHPET(AppleHPET *this)
{
  AppleHPET *v1; // rbx@1
  __int64 v2; // rax@1
  unsigned __int64 v3; // rcx@2
  __int64 v4; // rcx@2
  char v5; // r14@4
  __int64 v6; // rcx@9
  __int64 v7; // rdx@9
  __int64 v8; // rsi@10
  __int64 v10; // rax@16
  __int64 v11; // rax@16
  task *v12; // r8@17
  unsigned __int64 v13; // rdi@18
  int v14; // eax@19
  signed __int64 v15; // rsi@21
  __int64 v16; // r15@21
  __int64 v17; // rax@22
  signed __int64 v18; // r12@22
  __int64 v19; // rax@25
  unsigned int v20; // edx@25
  __int64 v21; // rax@25
  unsigned __int64 v22; // [sp+8h] [bp-28h]@5

  v1 = this;
  v2 = **((_QWORD **)this + 24);
  if ( (**((_QWORD **)this + 24) & 0x80FFLL) == 32769 )
  {
    *((_DWORD *)this + 53) = (((unsigned int)v2 >> 8) & 0x1F) + 1;
    *((_DWORD *)this + 54) = HIDWORD(v2);
    v3 = *(_QWORD *)(*((_QWORD *)this + 24) + 16LL) & 0xFFFFFFFFFFFFFFFCLL | 2;
    *((_QWORD *)this + 28) = v3;
    *(_QWORD *)(*((_QWORD *)this + 24) + 16LL) = v3;
    v4 = *((_QWORD *)this + 24);
    if ( !(*(_QWORD *)(v4 + 16) & 1) )
      *(_QWORD *)(v4 + 240) = 0LL;
    *(_QWORD *)(*((_QWORD *)this + 24) + 32LL) = 0xFFFFFFFFLL;
    v5 = 1;
    if ( (v2 & 0xFFFF0000) == 2156265472LL
      && !(*(int (__fastcall **)(_QWORD, unsigned __int64 *, signed __int64, signed __int64, signed __int64, _QWORD))(**((_QWORD **)this + 17) + 2336LL))(
            *((_QWORD *)this + 17),
            &v22,
            2LL,
            16252938LL,
            16LL,
            0LL)
      && (unsigned __int16)v22 == 1537
      && !(*(int (__fastcall **)(_QWORD, unsigned __int64 *, signed __int64, signed __int64, signed __int64, _QWORD))(**((_QWORD **)this + 17) + 2336LL))(
            *((_QWORD *)this + 17),
            &v22,
            2LL,
            16252928LL,
            32LL,
            0LL)
      && (unsigned __int16)v22 == 32902 )
    {
      v6 = 0LL;
      v7 = (__int64)AppleHPET::probeHPET(void)::ErrataTable;
      while ( 1 )
      {
        v8 = (unsigned int)(v22 >> 16) & *((_WORD *)AppleHPET::probeHPET(void)::ErrataTable + 2 * v6 + 1);
        if ( (_DWORD)v8 == *((_WORD *)AppleHPET::probeHPET(void)::ErrataTable + 2 * v6) )
          break;
        ++v6;
        if ( (unsigned int)v6 > 4 )
          goto LABEL_16;
      }
      *((_BYTE *)this + 240) = 1;
      v8 = (__int64)"UseTimer0";
      (*(void (__fastcall **)(AppleHPET *, _QWORD, _QWORD))(*(_QWORD *)this + 616LL))(
        this,
        "UseTimer0",
        **(_QWORD **)off_2050);
LABEL_16:
      LODWORD(v10) = (*(int (__fastcall **)(_QWORD, __int64, __int64))(**((_QWORD **)this + 18) + 312LL))(
                       *((_QWORD *)this + 18),
                       v8,
                       v7);
      LODWORD(v11) = (*(int (__fastcall **)(__int64, _QWORD, _QWORD, signed __int64))(*(_QWORD *)v10 + 312LL))(
                       v10,
                       0LL,
                       0LL,
                       2048LL);
      if ( v11 == 4275044352LL
        && !(*(int (__fastcall **)(_QWORD, __int64 *, signed __int64, signed __int64, signed __int64, _QWORD))(**((_QWORD **)this + 17) + 2336LL))(
              *((_QWORD *)this + 17),
              &v22,
              2LL,
              16253168LL,
              32LL,
              0LL) )
      {
        v13 = v22;
        if ( v22 & 1 )
        {
          v14 = v22 & 0xFFFFC000;
          v22 &= 0xFFFFFFFFFFFFC000LL;
          if ( v13 & 0xFFFFFFFFFFFFC000LL )
          {
            if ( v14 )
            {
              v15 = 4096LL;
              v16 = IOMemoryDescriptor::withAddressRange(
                      (IOMemoryDescriptor *)((unsigned int)v13 & 0xFFFFC000 | 0x3000LL),
                      0x1000uLL,
                      0x803uLL,
                      0,
                      v12);
              if ( v16 )
              {
                v15 = 0LL;
                LODWORD(v17) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v16 + 512LL))(v16, 0LL);
                v18 = (signed __int64)((char *)v1 + 152);
                *((_QWORD *)v1 + 19) = v17;
                (*(void (__fastcall **)(__int64))(*(_QWORD *)v16 + 40LL))(v16);
              }
              else
              {
                v18 = (signed __int64)((char *)v1 + 152);
              }
              if ( *(_QWORD *)v18 )
              {
                LODWORD(v19) = (*(int (__cdecl **)(_QWORD, signed __int64))(**(_QWORD **)v18 + 280LL))(
                                 *(_QWORD *)v18,
                                 v15);
                *((_QWORD *)v1 + 20) = v19 + 1028;
                v21 = OSNumber::withNumber(0LL, 0x20uLL, v20);
                *((_QWORD *)v1 + 21) = v21;
                if ( v21 )
                  (*(void (__fastcall **)(AppleHPET *, _QWORD, __int64))(*(_QWORD *)v1 + 616LL))(v1, "HPTC", v21);
              }
            }
          }
        }
      }
    }
  }
  else
  {
    v5 = 0;
  }
  return v5;
}
// 1FE0: using guessed type __int64 AppleHPET::probeHPET(void)::ErrataTable[2];
// 2050: using guessed type __int64 off_2050;

//----- (00000000000012FE) ----------------------------------------------------
int __fastcall AppleHPET::configureTimer(AppleHPET *this, __int64 a2)
{
  unsigned __int64 *v2; // r15@1
  unsigned __int64 v3; // r13@1
  int v4; // eax@1
  __int64 v5; // rbx@2
  unsigned __int64 v6; // r13@4
  int result; // eax@6
  unsigned __int64 v8; // r13@7
  signed int v9; // er15@8
  int v10; // ecx@14
  int v11; // [sp+Ch] [bp-44h]@7
  unsigned __int64 v12; // [sp+10h] [bp-40h]@7
  unsigned __int64 *v13; // [sp+18h] [bp-38h]@7
  unsigned int v14; // [sp+24h] [bp-2Ch]@2

  v2 = *(unsigned __int64 **)a2;
  v3 = **(_QWORD **)a2;
  v4 = AppleHPET::getInterruptVectorAtIndex(this, *(_DWORD *)(a2 + 8));
  if ( v4 < 0 )
  {
    v11 = v4;
    v13 = v2;
    v12 = v3;
    v8 = v3 >> 32;
    result = -536870210;
    v5 = 0LL;
    while ( 1 )
    {
      v9 = 1 << v5;
      if ( _bittest((const unsigned int *)&v8, v5) )
      {
        if ( !(v9 & *((_DWORD *)this + 52)) )
        {
          result = (*(int (__fastcall **)(AppleHPET *, _QWORD, _QWORD, _QWORD, __int64, _QWORD))(*(_QWORD *)this + 1728LL))(
                     this,
                     "InstallDeviceInterrupt",
                     0LL,
                     *((_QWORD *)this + 17),
                     v5,
                     0LL);
          if ( !result )
            break;
        }
      }
      ++v5;
      if ( (signed int)v5 >= 32 )
      {
        if ( result )
          return result;
        v2 = v13;
        v3 = v12;
        v4 = v11;
        goto LABEL_4;
      }
    }
    *((_DWORD *)this + 52) |= v9;
    v10 = AppleHPET::getInterruptVectorAtIndex(this, v14);
    result = -536870199;
    if ( v10 < 0 )
      return result;
    v2 = v13;
    v3 = v12;
    v4 = v10;
  }
  else
  {
    v14 = *(_DWORD *)(a2 + 8);
    LODWORD(v5) = -1;
    if ( v14 > 1 )
      LODWORD(v5) = v4;
  }
LABEL_4:
  *(_DWORD *)(a2 + 16) = v14;
  *(_DWORD *)(a2 + 20) = v4;
  v6 = v3 & 0xFFFFFFFFFFFF80F1LL;
  if ( (unsigned int)v5 <= 0x1F )
    v6 |= (_DWORD)v5 << 9;
  *v2 = v6;
  v2[1] = 0LL;
  *(_QWORD *)(a2 + 24) = v6;
  return 0;
}

//----- (000000000000142A) ----------------------------------------------------
char __fastcall AppleHPET::cpuDriverPublished(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v4; // r14@1
  __int64 v5; // r12@1
  __int64 v6; // rax@1
  int v7; // eax@1
  __int64 v8; // rax@3
  size_t v9; // rax@3
  size_t v10; // rax@4
  __int64 *v11; // rsi@9
  int v12; // ebx@9
  __int64 v13; // rax@14
  int v15; // [sp+8h] [bp-98h]@6
  __int64 v16; // [sp+10h] [bp-90h]@1
  __int64 v17; // [sp+18h] [bp-88h]@1
  __int64 v18; // [sp+20h] [bp-80h]@1
  int v19; // [sp+28h] [bp-78h]@1
  int v20; // [sp+2Ch] [bp-74h]@1
  char v21; // [sp+30h] [bp-70h]@5
  __int64 (__fastcall *v22)(AppleHPET *__hidden, unsigned int, void (*)(void), unsigned int *, unsigned int *, void **); // [sp+40h] [bp-60h]@3
  int (__fastcall *v23)(AppleHPET *, unsigned int); // [sp+48h] [bp-58h]@3
  __int64 (__fastcall *v24)(AppleHPET *, unsigned int, int); // [sp+50h] [bp-50h]@3
  __int64 (__fastcall *v25)(AppleHPET *__hidden); // [sp+58h] [bp-48h]@3
  __int64 (__fastcall *v26)(AppleHPET *__hidden); // [sp+60h] [bp-40h]@3
  char v27; // [sp+6Eh] [bp-32h]@3
  __int64 v28; // [sp+78h] [bp-28h]@1

  v4 = a4;
  v5 = off_2030[0];
  v28 = *(_QWORD *)off_2030[0];
  memset(&v16, 0, 0x58uLL);
  v16 = a1;
  v6 = *(_QWORD *)(a1 + 192);
  v17 = v6 + 240;
  v18 = v6 + 16;
  v19 = *(_DWORD *)(a1 + 216);
  v7 = *(_DWORD *)(a1 + 212);
  v20 = *(_DWORD *)(a1 + 212);
  if ( *(_BYTE *)(a1 + 240) )
    v20 = v7 - 1;
  v22 = AppleHPET::hpetTimerAcquire;
  v23 = AppleHPET::hpetTimerRelease;
  v24 = AppleHPET::hpetTimerCommand;
  v25 = AppleHPET::hpetSaveState;
  v26 = AppleHPET::hpetRestoreState;
  v8 = IOService::getPlatform((IOService *)&v16);
  (*(void (__fastcall **)(__int64, char *, signed __int64))(*(_QWORD *)v8 + 2232LL))(v8, &v27, 10LL);
  v9 = strlen("MacPro1,1");
  if ( !strncmp("MacPro1,1", &v27, v9) || (v10 = strlen("MacPro2,1"), !strncmp("MacPro2,1", &v27, v10)) )
    v21 |= 1u;
  if ( pmCPUControl(2148028421LL, &v15) )
  {
    kprintf("HPET: PMIOCIFVERSION error %d\n");
    IOLog("HPET: PMIOCIFVERSION error %d\n");
  }
  else if ( v15 == 261 )
  {
    v11 = &v16;
    v12 = pmCPUControl(2148028424LL, &v16);
    if ( v12 )
    {
      kprintf("HPET: PMIOCHPETREGISTER error %d\n");
      v11 = (__int64 *)(unsigned int)v12;
      IOLog("HPET: PMIOCHPETREGISTER error %d\n");
    }
    if ( v4 )
      (*(void (__fastcall **)(__int64, __int64 *))(*(_QWORD *)v4 + 288LL))(v4, v11);
  }
  else
  {
    kprintf("HPET: PMIOCIFVERSION mismatch. Expected 0x%04X, Got 0x%04X\n");
    IOLog("HPET: PMIOCIFVERSION mismatch. Expected 0x%04X, Got 0x%04X\n");
  }
  v13 = *(_QWORD *)v5;
  if ( *(_QWORD *)v5 == v28 )
    LOBYTE(v13) = 1;
  return v13;
}
// 2030: using guessed type __int64 off_2030[5];
// 9F98: using guessed type int __fastcall IOLog(_QWORD);
// A918: using guessed type int __fastcall kprintf(_QWORD);
// A928: using guessed type int __fastcall pmCPUControl(_QWORD, _QWORD);

//----- (0000000000001622) ----------------------------------------------------
int __fastcall AppleHPET::stop(AppleHPET *this, IOService *a2)
{
  return (*(int (__fastcall **)(AppleHPET *, IOService *))(off_2028[0] + 1496))(this, a2);
}
// 2028: using guessed type __int64 off_2028[6];

//----- (0000000000001634) ----------------------------------------------------
int __fastcall AppleHPET::free(AppleHPET *this)
{
  AppleHPET *v1; // rbx@1
  __int64 v2; // rdi@1
  __int64 v3; // rdi@3
  __int64 v4; // rdi@5
  __int64 v5; // rdi@7
  void *v6; // rdi@9
  __int64 v7; // rdi@12

  v1 = this;
  v2 = *((_QWORD *)this + 23);
  if ( v2 )
  {
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v2 + 280LL))(v2);
    *((_QWORD *)v1 + 23) = 0LL;
  }
  v3 = *((_QWORD *)v1 + 18);
  if ( v3 )
  {
    *((_QWORD *)v1 + 24) = 0LL;
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v3 + 40LL))(v3);
    *((_QWORD *)v1 + 18) = 0LL;
  }
  v4 = *((_QWORD *)v1 + 19);
  if ( v4 )
  {
    *((_QWORD *)v1 + 20) = 0LL;
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v4 + 40LL))(v4);
    *((_QWORD *)v1 + 19) = 0LL;
  }
  v5 = *((_QWORD *)v1 + 21);
  if ( v5 )
  {
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v5 + 40LL))(v5);
    *((_QWORD *)v1 + 21) = 0LL;
  }
  v6 = (void *)*((_QWORD *)v1 + 25);
  if ( v6 && *((_DWORD *)v1 + 53) )
  {
    memset(v6, 0, 40LL * *((_DWORD *)v1 + 53));
    IOFree(*((_QWORD *)v1 + 25), 40LL * *((_DWORD *)v1 + 53));
    *((_QWORD *)v1 + 25) = 0LL;
  }
  v7 = *((_QWORD *)v1 + 22);
  if ( v7 )
  {
    IOLockFree(v7);
    *((_QWORD *)v1 + 22) = 0LL;
  }
  return (*(int (__fastcall **)(AppleHPET *))(off_2028[0] + 160))(v1);
}
// 2028: using guessed type __int64 off_2028[6];
// 9F70: using guessed type int __fastcall IOFree(_QWORD, _QWORD);
// 9F80: using guessed type int __cdecl IOLockFree(_QWORD);

//----- (0000000000001748) ----------------------------------------------------
__int64 __fastcall AppleHPET::hpetTimerAcquire(AppleHPET *this, unsigned int a2, void (*a3)(void), unsigned int *a4, unsigned int *a5, void **a6)
{
  void **v6; // r15@1
  unsigned int *v7; // r13@1
  void (*v8)(void); // r12@1
  bool v9; // cl@1
  signed int v10; // er14@1
  unsigned int v11; // eax@3
  unsigned int v12; // ecx@4
  __int64 v13; // r13@4
  __int64 v14; // r15@7
  __int64 v16; // [sp+8h] [bp-48h]@12
  unsigned int *v17; // [sp+10h] [bp-40h]@4
  void **v18; // [sp+18h] [bp-38h]@4
  unsigned int *v19; // [sp+20h] [bp-30h]@3

  v6 = a6;
  v7 = a4;
  v8 = a3;
  v9 = a4 == 0LL;
  v10 = -1;
  if ( a2 != -1 && a6 != 0LL && a5 != 0LL && !v9 && a3 != 0LL )
  {
    v19 = a5;
    IOLockLock(*((_QWORD *)this + 22));
    v11 = *((_DWORD *)this + 53);
    if ( !v11 )
      goto LABEL_14;
    v17 = v7;
    v18 = v6;
    v12 = 0;
    v13 = 0LL;
    while ( 1 )
    {
      if ( v12 || !*((_BYTE *)this + 240) )
      {
        v14 = *((_QWORD *)this + 25);
        if ( *(_DWORD *)(v14 + v13 + 12) == -1 && *(_DWORD *)(v14 + v13 + 16) != -1 )
          break;
      }
      v13 += 40LL;
      ++v12;
      if ( v12 >= v11 )
        goto LABEL_14;
    }
    if ( v13 + v14
      && (v16 = v13 + v14, !AppleHPET::setInterruptMessageDestination(this, v13 + v14, a2))
      && !(*(int (__fastcall **)(_QWORD, _QWORD, AppleHPET *, void (*)(void), _QWORD))(**((_QWORD **)this + 17) + 1784LL))(
            *((_QWORD *)this + 17),
            *(_DWORD *)(v16 + 16),
            this,
            v8,
            0LL) )
    {
      v10 = -1;
      if ( (*(int (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)this + 17) + 1808LL))(
             *((_QWORD *)this + 17),
             *(_DWORD *)(v16 + 16)) )
      {
        (*(void (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)this + 17) + 1792LL))(
          *((_QWORD *)this + 17),
          *(_DWORD *)(v16 + 16));
      }
      else
      {
        *(_DWORD *)(v14 + v13 + 12) = a2;
        *v19 = ((unsigned int)**(_QWORD **)(v14 + v13) >> 5) & 1;
        *v17 = *(_DWORD *)(v14 + v13 + 8);
        *v18 = (void *)(*(_QWORD *)(v14 + v13) + 8LL);
        v10 = 0;
      }
    }
    else
    {
LABEL_14:
      v10 = -1;
    }
    IOLockUnlock(*((_QWORD *)this + 22));
  }
  return (unsigned int)v10;
}
// 9F88: using guessed type int __fastcall IOLockLock(_QWORD);
// 9F90: using guessed type int __fastcall IOLockUnlock(_QWORD);

//----- (00000000000018D8) ----------------------------------------------------
int __fastcall AppleHPET::hpetTimerRelease(AppleHPET *this, unsigned int a2)
{
  __int64 v2; // r15@2
  unsigned __int64 v3; // rax@3
  int result; // eax@4

  if ( *((_DWORD *)this + 53) > a2 )
  {
    IOLockLock(*((_QWORD *)this + 22));
    v2 = *((_QWORD *)this + 25);
    if ( *(_DWORD *)(v2 + 40LL * a2 + 12) != -1 )
    {
      v3 = *(_QWORD *)(v2 + 40LL * a2 + 24) & 0xFFFFFFFFFFFFFFFBLL;
      *(_QWORD *)(v2 + 40LL * a2 + 24) = v3;
      **(_QWORD **)(v2 + 40LL * a2) = v3;
      (*(void (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)this + 17) + 1816LL))(
        *((_QWORD *)this + 17),
        *(_DWORD *)(v2 + 40LL * a2 + 16));
      (*(void (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)this + 17) + 1792LL))(
        *((_QWORD *)this + 17),
        *(_DWORD *)(v2 + 40LL * a2 + 16));
      *(_DWORD *)(v2 + 40LL * a2 + 12) = -1;
    }
    result = IOLockUnlock(*((_QWORD *)this + 22));
  }
  return result;
}
// 9F88: using guessed type int __fastcall IOLockLock(_QWORD);
// 9F90: using guessed type int __fastcall IOLockUnlock(_QWORD);

//----- (0000000000001980) ----------------------------------------------------
__int64 __fastcall AppleHPET::hpetTimerCommand(AppleHPET *this, unsigned int a2, int a3)
{
  __int64 result; // rax@1
  __int64 v4; // r8@2
  signed __int64 v5; // r10@3
  unsigned __int64 v6; // rax@4

  result = 0xFFFFFFFFLL;
  if ( *((_DWORD *)this + 53) > a2 )
  {
    v4 = *((_QWORD *)this + 25);
    result = 4294967294LL;
    if ( *(_DWORD *)(v4 + 40LL * a2 + 12) != -1 )
    {
      v5 = v4 + 40LL * a2;
      if ( a3 )
      {
        result = 4294967293LL;
        if ( a3 != 1 )
          return result;
        *(_QWORD *)(*((_QWORD *)this + 24) + 32LL) = 1 << a2;
        *(_BYTE *)(v4 + 40LL * a2 + 24) |= 4u;
        *(_QWORD *)(*(_QWORD *)v5 + 8LL) = 0LL;
        v6 = *(_QWORD *)(v4 + 40LL * a2 + 24);
      }
      else
      {
        v6 = *(_QWORD *)(v4 + 40LL * a2 + 24) & 0xFFFFFFFFFFFFFFFBLL;
        *(_QWORD *)(v4 + 40LL * a2 + 24) = v6;
      }
      **(_QWORD **)v5 = v6;
      result = 0LL;
    }
  }
  return result;
}

//----- (0000000000001A04) ----------------------------------------------------
__int64 __fastcall AppleHPET::hpetSaveState(AppleHPET *this)
{
  unsigned int v1; // er8@1
  signed __int64 v2; // rdx@2
  signed __int64 v3; // rcx@2
  unsigned int v4; // esi@2
  __int64 result; // rax@4

  v1 = *((_DWORD *)this + 53);
  if ( v1 )
  {
    v2 = *((_QWORD *)this + 24) + 264LL;
    v3 = *((_QWORD *)this + 25) + 32LL;
    v4 = 0;
    do
    {
      *(_QWORD *)v3 = *(_QWORD *)v2;
      v2 += 32LL;
      v3 += 40LL;
      ++v4;
    }
    while ( v4 < v1 );
  }
  *((_QWORD *)this + 29) = *(_QWORD *)(*((_QWORD *)this + 24) + 240LL);
  result = *(_QWORD *)(*((_QWORD *)this + 24) + 16LL);
  *((_QWORD *)this + 28) = result;
  return result;
}

//----- (0000000000001A6C) ----------------------------------------------------
__int64 __fastcall AppleHPET::hpetRestoreState(AppleHPET *this)
{
  __int64 v1; // rax@1
  __int64 v2; // rax@3
  unsigned int v3; // eax@8
  signed __int64 v4; // rcx@9
  signed __int64 v5; // rdx@9
  unsigned int v6; // esi@9
  __int64 result; // rax@11

  v1 = *((_QWORD *)this + 24);
  if ( !*(_QWORD *)v1 || *(_QWORD *)v1 == -1LL )
  {
    v2 = *((_QWORD *)this + 20);
    if ( !(*(_DWORD *)v2 & 0x80) )
      *(_DWORD *)v2 = *(_DWORD *)v2 & 0xFFFFFF7C | 0x80;
    if ( !(**((_DWORD **)this + 20) & 0x80) )
    {
      //kprintf("HPET: enable failed\n");
      IOLog("HPET: enable failed\n");
    }
    (*(void (__fastcall **)(_QWORD, signed __int64))(**((_QWORD **)this + 21) + 344LL))(*((_QWORD *)this + 21), 1LL);
  }
  *(_QWORD *)(*((_QWORD *)this + 24) + 16LL) = *((_QWORD *)this + 28);
  v3 = *((_DWORD *)this + 53);
  if ( v3 )
  {
    v4 = *((_QWORD *)this + 25) + 32LL;
    v5 = *((_QWORD *)this + 24) + 264LL;
    v6 = 0;
    do
    {
      *(_QWORD *)(v5 - 8) = *(_QWORD *)(v4 - 8);
      *(_QWORD *)v5 = *(_QWORD *)v4;
      v4 += 40LL;
      v5 += 32LL;
      ++v6;
    }
    while ( v6 < v3 );
  }
  *(_QWORD *)(*((_QWORD *)this + 24) + 32LL) = 0xFFFFFFFFLL;
  result = *((_QWORD *)this + 24);
  *(_QWORD *)(result + 240) = *((_QWORD *)this + 29);
  return result;
}
// 9F98: using guessed type int __fastcall IOLog(_QWORD);
// A918: using guessed type int __fastcall kprintf(_QWORD);

//----- (0000000000001B60) ----------------------------------------------------
int __fastcall AppleHPET::setInterruptMessageDestination(AppleHPET *a1, __int64 a2, unsigned int a3)
{
  unsigned int v3; // er14@1
  __int64 v4; // rbx@1
  __int64 v5; // rax@1
  int result; // eax@3

  v3 = a3;
  v4 = *(_DWORD *)(a2 + 20);
  LODWORD(v5) = AppleHPET::getInterruptControllerAtIndex(a1, *(_DWORD *)(a2 + 16));
  if ( v4 && v5 )
    result = (*(int (__fastcall **)(__int64, _QWORD, _QWORD, __int64, _QWORD, _QWORD))(*(_QWORD *)v5 + 1728LL))(
               v5,
               "SetVectorPhysicalDestination",
               0LL,
               v4,
               v3,
               0LL);
  else
    result = -536870199;
  return result;
}

//----- (0000000000001BBC) ----------------------------------------------------
__int64 __fastcall AppleHPET::getInterruptVectorAtIndex(AppleHPET *this, unsigned int a2)
{
  __int64 v2; // rax@1
  __int64 v3; // rax@1
  __int64 v4; // rbx@1
  signed int v5; // er15@1
  __int64 v6; // rax@3
  __int64 v7; // rax@3
  __int64 v8; // rbx@3
  signed int *v9; // rax@5

  LODWORD(v2) = (*(int (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)this + 17) + 680LL))(
                  *((_QWORD *)this + 17),
                  *(_QWORD *)off_2048[0]);
  LODWORD(v3) = OSMetaClassBase::safeMetaCast(v2, *(_QWORD *)off_2010[0]);
  v4 = v3;
  v5 = -1;
  if ( v3 )
  {
    if ( (*(int (__fastcall **)(__int64))(*(_QWORD *)v3 + 304LL))(v3) )
    {
      LODWORD(v6) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v4 + 488LL))(v4, a2);
      LODWORD(v7) = OSMetaClassBase::safeMetaCast(v6, *(_QWORD *)off_2008[0]);
      v8 = v7;
      if ( v7 )
      {
        if ( (unsigned int)(*(int (__fastcall **)(__int64))(*(_QWORD *)v7 + 320LL))(v7) >= 4 )
        {
          LODWORD(v9) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v8 + 376LL))(v8);
          v5 = *v9;
        }
      }
    }
  }
  return (unsigned int)v5;
}
// 2008: using guessed type _QWORD off_2008[10];
// 2010: using guessed type _QWORD off_2010[9];
// 2048: using guessed type __int64 off_2048[2];
// A1B8: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);

//----- (0000000000001C6A) ----------------------------------------------------
IOReturn AppleHPET::getInterruptControllerAtIndex(AppleHPET *this, uint32_t index)
{
  uint32_t v2; // er14@1
  uint64_t v3; // rax@1
  uint64_t v4; // rsi@1
  uint64_t v5; // rax@1
  uint64_t v6; // rbx@1
  uint32_t v8; // ecx@2
  uint64_t v11; // rax@3
  uint64_t v12; // rbx@3
  uint64_t v13; // rax@4
  IOService *v9; // rax@3
  IOService *v10; // rdi@3
  OSReturn result; // eax@1

  v2 = index;

  LODWORD(v3) = (*(UInt64 (__fastcall **)(UInt64, UInt64))(**((UInt64 **)this + 17) + 680LL))(
                  *((UInt64 *)this + 17),
                  *(UInt64 *)off_2040[0]);
  v4 = *(UInt64 *)off_2010[0];
  LODWORD(v5) = OSMetaClassBase::safeMetaCast(v3, *(_QWORD *)off_2010[0]);
  v6 = v5;
  result = 0;
  if ( v6 )
  {
    v8 = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v6 + 304LL))(v6, v4);
    result = 0;
    if ( v8 )
    {
      LODWORD(v9) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v6 + 488LL))(v6, v2);
      v10 = v9;
      LODWORD(v11) = OSMetaClassBase::safeMetaCast(v9, *(_QWORD *)off_2018[0]);
      v12 = v11;
      result = 0;
      if ( v12 )
      {
        v13 = IOService::getPlatform(v10);
        result = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v13 + 2312LL))(v13, v12);
      }
    }
  }
  return result;
}
// 2010: using guessed type _QWORD off_2010[9];
// 2018: using guessed type _QWORD off_2018[8];
// 2040: using guessed type __int64 off_2040[3];
// A1B8: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);

//----- (0000000000001D02) ----------------------------------------------------
/*__int64 __fastcall AppleHPET::MetaClass::~MetaClass(AppleHPET::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}*/

//----- (0000000000001D10) ----------------------------------------------------
/*__int64 `global constructor keyed to'_a()
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(&AppleHPET::gMetaClass, "AppleHPET", off_2020[0], 248LL);
  result = (__int64)off_2900;
  AppleHPET::gMetaClass = off_2900;
  return result;
}*/
// 2020: using guessed type _QWORD off_2020[7];
// 2900: using guessed type __int64 (__fastcall *off_2900[2])(AppleHPET::MetaClass *__hidden this);
// 2AA0: using guessed type _QWORD AppleHPET::gMetaClass;
// 9FE8: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001D50) ----------------------------------------------------
/*__int64 `global destructor keyed to'_a()
{
  return OSMetaClass::~OSMetaClass((OSMetaClass *)&AppleHPET::gMetaClass);
}*/
