/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall AppleHPET::MetaClass::MetaClass(AppleHPET::MetaClass *__hidden this); // idb
__int64 __fastcall AppleHPET::AppleHPET(__int64 a1);
__int64 __fastcall AppleHPET::AppleHPET(__int64 a1);
__int64 *__fastcall AppleHPET::~AppleHPET(AppleHPET *this);
__int64 *__fastcall AppleHPET::~AppleHPET(AppleHPET *this);
__int64 *__fastcall AppleHPET::~AppleHPET(AppleHPET *this);
__int64 *__fastcall AppleHPET::getMetaClass(AppleHPET *this);
__int64 __fastcall AppleHPET::MetaClass::MetaClass(AppleHPET::MetaClass *__hidden this); // idb
// __int64 __usercall AppleHPET::MetaClass::alloc@<rax>(AppleHPET::MetaClass *this@<rdi>, __int64 result@<rax>);
char __fastcall AppleHPET::AppleHPET(__int64 a1);
char __fastcall AppleHPET::AppleHPET(__int64 a1);
char __fastcall AppleHPET::start(AppleHPET *this, __int64 a2);
char __fastcall AppleHPET::probeHPET(AppleHPET *this);
int __fastcall AppleHPET::configureTimer(AppleHPET *this, __int64 a2, __int64 a3);
char __fastcall AppleHPET::cpuDriverPublished(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
int AppleHPET::stop();
void __fastcall AppleHPET::free(AppleHPET *this);
__int64 __fastcall AppleHPET::hpetTimerAcquire(AppleHPET *this, int a2, void (*a3)(void), unsigned int *a4, unsigned int *a5, void **a6);
int __fastcall AppleHPET::hpetTimerRelease(AppleHPET *this, int a2);
__int64 __fastcall AppleHPET::hpetTimerCommand(AppleHPET *this, unsigned int a2, int a3);
__int64 __fastcall AppleHPET::hpetSaveState(AppleHPET *__hidden this); // idb
__int64 __fastcall AppleHPET::hpetRestoreState(AppleHPET *__hidden this); // idb
int __fastcall AppleHPET::setInterruptMessageDestination(AppleHPET *a1, __int64 a2, __int64 a3);
__int64 __fastcall AppleHPET::getInterruptVectorAtIndex(AppleHPET *this, unsigned int a2, __int64 a3);
int __fastcall AppleHPET::getInterruptControllerAtIndex(AppleHPET *this, unsigned int a2, __int64 a3);
int start();
char *OSKextGetCurrentIdentifier();
char *OSKextGetCurrentVersionString();
__int64 OSKextGetCurrentLoadTag();
int stop();

//-------------------------------------------------------------------------
// Data declarations

// 0xFFFF3A16
// 0xFFFF3A14
// 0xFFFF3A1A
// 0xFFFF3A18
unsigned __int32 dword_1450[4] = { 0xFFFF3A16, 0xFFFF3A14, 0xFFFF3A1A, 0xFFFF3A18 }; // weak
__int64 qword_1450[2] = { -217604518102508LL, -217587338233320LL }; // weak
__int64 qword_1470 = 0LL; // weak
__int64 qword_1478 = 0LL; // weak
__int64 qword_1480 = 0LL; // weak
__int64 qword_1488 = 0LL; // weak
__int64 qword_1498 = 0LL; // weak
__int64 qword_14A0 = 0LL; // weak
__int64 qword_14A8 = 0LL; // weak
__int64 qword_14B0 = 0LL; // weak
__int64 qword_14B8 = 0LL; // weak
__int64 (*off_14C0)[8] = &qword_1D10; // weak
__int64 qword_1500[5] = { 0LL, 0LL, 0LL, 0LL, 0LL }; // weak
__int64 qword_1D70[15] = { 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL, 0LL }; // weak
char aCom_apple_driv[27] = "com.apple.driver.AppleHPET"; // weak
__int64 qword_1F10; // weak


//----- (0000000000000000) ----------------------------------------------------
__int64 __fastcall AppleHPET::MetaClass::MetaClass(AppleHPET::MetaClass *this)
{
  __int64 result; // rax@1

  result = (__int64)qword_1D70;
  *(_QWORD *)this = qword_1D70;
  return result;
}
// 1D70: using guessed type __int64 qword_1D70[15];

//----- (000000000000003C) ----------------------------------------------------
__int64 __fastcall AppleHPET::AppleHPET(__int64 a1)
{
  __int64 result; // rax@1

  result = (__int64)qword_1500;
  *(_QWORD *)a1 = qword_1500;
  return result;
}
// 1500: using guessed type __int64 qword_1500[5];

//----- (000000000000005C) ----------------------------------------------------
__int64 __fastcall AppleHPET::AppleHPET(__int64 a1)
{
  __int64 result; // rax@1

  result = (__int64)qword_1500;
  *(_QWORD *)a1 = qword_1500;
  return result;
}
// 1500: using guessed type __int64 qword_1500[5];

//----- (000000000000007C) ----------------------------------------------------
__int64 *__fastcall AppleHPET::~AppleHPET(AppleHPET *this)
{
  return AppleHPET::~AppleHPET(this);
}

//----- (0000000000000086) ----------------------------------------------------
__int64 *__fastcall AppleHPET::~AppleHPET(AppleHPET *this)
{
  return AppleHPET::~AppleHPET(this);
}

//----- (0000000000000090) ----------------------------------------------------
__int64 *__fastcall AppleHPET::~AppleHPET(AppleHPET *this)
{
  return AppleHPET::getMetaClass(this);
}

//----- (00000000000000B2) ----------------------------------------------------
__int64 *__fastcall AppleHPET::getMetaClass(AppleHPET *this)
{
  return &qword_1F10;
}
// 1F10: using guessed type __int64 qword_1F10;

//----- (00000000000000C0) ----------------------------------------------------
__int64 __fastcall AppleHPET::MetaClass::MetaClass(AppleHPET::MetaClass *this)
{
  __int64 result; // rax@1

  result = (__int64)qword_1D70;
  *(_QWORD *)this = qword_1D70;
  return result;
}
// 1D70: using guessed type __int64 qword_1D70[15];

//----- (00000000000000F2) ----------------------------------------------------
__int64 __usercall AppleHPET::MetaClass::alloc@<rax>(AppleHPET::MetaClass *this@<rdi>, __int64 result@<rax>)
{
  *(_QWORD *)result = qword_1500;
  return result;
}
// 1500: using guessed type __int64 qword_1500[5];

//----- (0000000000000132) ----------------------------------------------------
char __fastcall AppleHPET::AppleHPET(__int64 a1)
{
  *(_QWORD *)a1 = qword_1500;
  return AppleHPET::AppleHPET((__int64)&qword_1F10);
}
// 1500: using guessed type __int64 qword_1500[5];
// 1F10: using guessed type __int64 qword_1F10;

//----- (0000000000000162) ----------------------------------------------------
char __fastcall AppleHPET::AppleHPET(__int64 a1)
{
  *(_QWORD *)a1 = qword_1500;
  return AppleHPET::start((AppleHPET *)&qword_1F10, (__int64)&qword_1F10);
}
// 1500: using guessed type __int64 qword_1500[5];
// 1F10: using guessed type __int64 qword_1F10;

//----- (0000000000000192) ----------------------------------------------------
char __fastcall AppleHPET::start(AppleHPET *this, __int64 a2)
{
  __int64 v2; // r14@1
  AppleHPET *v3; // rbx@1
  __int64 v4; // r12@1
  __int64 v5; // rax@1
  __int64 v6; // rax@3
  __int64 v7; // rsi@3
  char *v8; // r13@3
  __int64 v9; // rax@5
  __int64 v10; // rax@6
  __int64 v11; // rdx@6
  unsigned __int64 v12; // rax@7
  __int64 v13; // rdx@7
  char result; // al@13
  __int64 v15; // rax@15
  __int64 v16; // rdx@15
  signed __int64 v17; // rax@16
  unsigned int v18; // er15@17
  signed __int64 v19; // r13@17
  __int64 v20; // r12@18
  __int64 v21; // rdi@22
  signed __int64 v22; // r12@22

  v2 = a2;
  v3 = this;
  v4 = qword_1498;
  LODWORD(v5) = (*(int (__cdecl **)(AppleHPET *))(qword_1498 + 1488))(this);
  if ( !(_BYTE)v5 )
    return 0;
  *((_QWORD *)this + 22) = v5;
  if ( !v5 )
  {
    v8 = (char *)this + 136;
    goto LABEL_10;
  }
  v6 = qword_1470;
  v7 = *(_QWORD *)qword_1470;
  v8 = (char *)this + 136;
  *((_QWORD *)this + 17) = qword_1470;
  if ( !v6
    || !(unsigned __int8)(*(int (__fastcall **)(__int64, AppleHPET *, _QWORD, _QWORD))(*(_QWORD *)v6 + 1488LL))(
                           v6,
                           this,
                           0LL,
                           0LL)
    || (LODWORD(v9) = (*(int (__fastcall **)(_QWORD, _QWORD, signed __int64))(**((_QWORD **)this + 17) + 1760LL))(
                        *((_QWORD *)this + 17),
                        0LL,
                        256LL),
        (*((_QWORD *)this + 18) = v9) == 0LL)
    || (LODWORD(v10) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v9 + 280LL))(v9), !v10)
    || (LODWORD(v12) = (*(int (__cdecl **)(_QWORD, _QWORD, __int64))(**((_QWORD **)this + 18) + 296LL))(
                         *((_QWORD *)this + 18),
                         0LL,
                         v11),
        v12 <= 0x3FF)
    || (LODWORD(v15) = (*(int (__cdecl **)(_QWORD, _QWORD, __int64))(**((_QWORD **)this + 18) + 280LL))(
                         *((_QWORD *)this + 18),
                         0LL,
                         v13),
        *((_QWORD *)this + 24) = v15,
        !AppleHPET::probeHPET(this))
    || (v17 = 8LL * *((_DWORD *)this + 53), (*((_QWORD *)this + 25) = v17) == 0LL) )
  {
LABEL_10:
    if ( *(_QWORD *)v8 )
      (*(void (__fastcall **)(_QWORD, AppleHPET *, _QWORD))(**(_QWORD **)v8 + 1496LL))(*(_QWORD *)v8, v3, 0LL);
    (*(void (__fastcall **)(AppleHPET *, __int64))(v4 + 1496))(v3, v2);
    return 0;
  }
  v18 = 0;
  v19 = 256LL;
  if ( *((_DWORD *)this + 53) )
  {
    v20 = 0LL;
    while ( 1 )
    {
      *(_QWORD *)(v17 + v20) = v19 + *((_QWORD *)this + 24);
      *(_DWORD *)(v17 + v20 + 8) = v18;
      *(_DWORD *)(v17 + v20 + 12) = -1;
      *(_DWORD *)(v17 + v20 + 16) = -1;
      *(_DWORD *)(v17 + v20 + 20) = 0;
      *(_QWORD *)(v17 + v20 + 24) = 0LL;
      *(_QWORD *)(v17 + v20 + 32) = 0LL;
      LODWORD(v17) = AppleHPET::configureTimer(this, v17 + v20, v16);
      ++v18;
      if ( v18 >= *((_DWORD *)this + 53) )
        break;
      v17 = *((_QWORD *)this + 25);
      v20 += 40LL;
      v19 += 32LL;
    }
  }
  v8 = (char *)this + 136;
  if ( v17 )
  {
    v21 = *(_QWORD *)qword_14A8;
    v22 = (signed __int64)((char *)v3 + 184);
    *((_QWORD *)v3 + 23) = qword_14A8;
    (*(void (__fastcall **)(signed __int64, signed __int64, char (__fastcall *)(__int64, __int64, __int64, __int64), AppleHPET *, _QWORD, _QWORD))(*(_QWORD *)v17 + 40LL))(
      v17,
      v17,
      AppleHPET::cpuDriverPublished,
      v3,
      0LL,
      0LL);
  }
  else
  {
    v22 = (signed __int64)((char *)this + 184);
  }
  result = 1;
  if ( !*(_QWORD *)v22 )
  {
    v4 = qword_1498;
    goto LABEL_10;
  }
  return result;
}
// 1470: using guessed type __int64 qword_1470;
// 1498: using guessed type __int64 qword_1498;
// 14A8: using guessed type __int64 qword_14A8;

//----- (000000000000048E) ----------------------------------------------------
char __fastcall AppleHPET::probeHPET(AppleHPET *this)
{
  AppleHPET *v1; // rbx@1
  __int64 v2; // rax@1
  unsigned __int64 v3; // rcx@2
  __int64 v4; // rcx@2
  char v5; // r14@4
  __int64 v6; // rcx@9
  __int64 v7; // rdx@9
  __int64 v8; // rsi@10
  __int64 v10; // rax@16
  __int64 v11; // rax@16
  unsigned __int64 v12; // rdi@18
  unsigned __int64 v13; // rax@19
  signed __int64 v14; // rsi@21
  signed __int64 v15; // rdx@21
  unsigned __int64 v16; // r15@21
  __int64 v17; // rax@22
  signed __int64 v18; // r12@22
  __int64 v19; // rax@25
  signed __int64 v20; // rax@25
  unsigned __int64 v21; // [sp+8h] [bp-28h]@5

  v1 = this;
  v2 = **((_QWORD **)this + 24);
  if ( (**((_QWORD **)this + 24) & 0x80FFLL) == 32769 )
  {
    *((_DWORD *)this + 53) = (((unsigned int)v2 >> 8) & 0x1F) + 1;
    *((_DWORD *)this + 54) = HIDWORD(v2);
    v3 = *(_QWORD *)(*((_QWORD *)this + 24) + 16LL) & 0xFFFFFFFFFFFFFFFCLL | 2;
    *((_QWORD *)this + 28) = v3;
    *(_QWORD *)(*((_QWORD *)this + 24) + 16LL) = v3;
    v4 = *((_QWORD *)this + 24);
    if ( !(*(_QWORD *)(v4 + 16) & 1) )
      *(_QWORD *)(v4 + 240) = 0LL;
    *(_QWORD *)(*((_QWORD *)this + 24) + 32LL) = 0xFFFFFFFFLL;
    v5 = 1;
    if ( (v2 & 0xFFFF0000) == 2156265472LL
      && !(*(int (__fastcall **)(_QWORD, unsigned __int64 *, signed __int64, signed __int64, signed __int64, _QWORD))(**((_QWORD **)this + 17) + 2336LL))(
            *((_QWORD *)this + 17),
            &v21,
            2LL,
            16252938LL,
            16LL,
            0LL)
      && (unsigned __int16)v21 == 1537
      && !(*(int (__fastcall **)(_QWORD, unsigned __int64 *, signed __int64, signed __int64, signed __int64, _QWORD))(**((_QWORD **)this + 17) + 2336LL))(
            *((_QWORD *)this + 17),
            &v21,
            2LL,
            16252928LL,
            32LL,
            0LL)
      && (unsigned __int16)v21 == 32902 )
    {
      v6 = 0LL;
      v7 = (__int64)qword_1450;
      while ( 1 )
      {
        v8 = (unsigned int)(v21 >> 16) & *((_WORD *)qword_1450 + 2 * v6 + 1);
        if ( (_DWORD)v8 == *((_WORD *)qword_1450 + 2 * v6) )
          break;
        ++v6;
        if ( (unsigned int)v6 > 4 )
          goto LABEL_16;
      }
      *((_BYTE *)this + 240) = 1;
      v8 = (__int64)"UseTimer0";
      (*(void (__fastcall **)(AppleHPET *, _QWORD, _QWORD))(*(_QWORD *)this + 616LL))(
        this,
        "UseTimer0",
        *(_QWORD *)(*off_14C0)[0]);
LABEL_16:
      LODWORD(v10) = (*(int (__fastcall **)(_QWORD, __int64, __int64))(**((_QWORD **)this + 18) + 312LL))(
                       *((_QWORD *)this + 18),
                       v8,
                       v7);
      LODWORD(v11) = (*(int (__fastcall **)(__int64, _QWORD, _QWORD, signed __int64))(*(_QWORD *)v10 + 312LL))(
                       v10,
                       0LL,
                       0LL,
                       2048LL);
      if ( v11 == 4275044352LL
        && !(*(int (__fastcall **)(_QWORD, __int64 *, signed __int64, signed __int64, signed __int64, _QWORD))(**((_QWORD **)this + 17) + 2336LL))(
              *((_QWORD *)this + 17),
              &v21,
              2LL,
              16253168LL,
              32LL,
              0LL) )
      {
        v12 = v21;
        if ( v21 & 1 )
        {
          v13 = v21 & 0xFFFFFFFFFFFFC000LL;
          v21 &= 0xFFFFFFFFFFFFC000LL;
          if ( v12 & 0xFFFFFFFFFFFFC000LL )
          {
            if ( (_DWORD)v13 )
            {
              v14 = 4096LL;
              v15 = 2051LL;
              v16 = v13;
              if ( v13 )
              {
                v14 = 0LL;
                LODWORD(v17) = (*(int (__fastcall **)(unsigned __int64, _QWORD, signed __int64, _QWORD))(*(_QWORD *)v13 + 512LL))(
                                 v13,
                                 0LL,
                                 2051LL,
                                 0LL);
                v18 = (signed __int64)((char *)v1 + 152);
                *((_QWORD *)v1 + 19) = v17;
                (*(void (__fastcall **)(unsigned __int64))(*(_QWORD *)v16 + 40LL))(v16);
              }
              else
              {
                v18 = (signed __int64)((char *)v1 + 152);
              }
              if ( *(_QWORD *)v18 )
              {
                LODWORD(v19) = (*(int (__cdecl **)(_QWORD, signed __int64, signed __int64))(**(_QWORD **)v18 + 280LL))(
                                 *(_QWORD *)v18,
                                 v14,
                                 v15);
                v20 = v19 + 1028;
                *((_QWORD *)v1 + 20) = v20;
                *((_QWORD *)v1 + 21) = v20;
                if ( v20 )
                  (*(void (__fastcall **)(AppleHPET *, _QWORD, signed __int64))(*(_QWORD *)v1 + 616LL))(v1, "HPTC", v20);
              }
            }
          }
        }
      }
    }
  }
  else
  {
    v5 = 0;
  }
  return v5;
}
// 1450: using guessed type __int64 qword_1450[2];
// 14C0: using guessed type __int64 (*off_14C0)[8];

//----- (000000000000076E) ----------------------------------------------------
int __fastcall AppleHPET::configureTimer(AppleHPET *this, __int64 a2, __int64 a3)
{
  unsigned __int64 *v3; // r15@1
  unsigned __int64 v4; // r13@1
  int v5; // eax@1
  __int64 v6; // rbx@2
  unsigned __int64 v7; // r13@4
  int result; // eax@6
  unsigned __int64 v9; // r13@7
  signed int v10; // er15@8
  __int64 v11; // rdx@10
  int v12; // ecx@14
  int v13; // [sp+Ch] [bp-44h]@7
  unsigned __int64 v14; // [sp+10h] [bp-40h]@7
  unsigned __int64 *v15; // [sp+18h] [bp-38h]@7
  unsigned int v16; // [sp+24h] [bp-2Ch]@2

  v3 = *(unsigned __int64 **)a2;
  v4 = **(_QWORD **)a2;
  v5 = AppleHPET::getInterruptVectorAtIndex(this, *(_DWORD *)(a2 + 8), a3);
  if ( v5 < 0 )
  {
    v13 = v5;
    v15 = v3;
    v14 = v4;
    v9 = v4 >> 32;
    result = -536870210;
    v6 = 0LL;
    while ( 1 )
    {
      v10 = 1 << v6;
      if ( _bittest((const unsigned int *)&v9, v6) )
      {
        if ( !(v10 & *((_DWORD *)this + 52)) )
        {
          result = (*(int (__fastcall **)(AppleHPET *, _QWORD, _QWORD, _QWORD, __int64, _QWORD))(*(_QWORD *)this + 1728LL))(
                     this,
                     "InstallDeviceInterrupt",
                     0LL,
                     *((_QWORD *)this + 17),
                     v6,
                     0LL);
          if ( !result )
            break;
        }
      }
      ++v6;
      if ( (signed int)v6 >= 32 )
      {
        if ( result )
          return result;
        v3 = v15;
        v4 = v14;
        v5 = v13;
        goto LABEL_4;
      }
    }
    *((_DWORD *)this + 52) |= v10;
    v12 = AppleHPET::getInterruptVectorAtIndex(this, v16, v11);
    result = -536870199;
    if ( v12 < 0 )
      return result;
    v3 = v15;
    v4 = v14;
    v5 = v12;
  }
  else
  {
    v16 = *(_DWORD *)(a2 + 8);
    LODWORD(v6) = -1;
    if ( v16 > 1 )
      LODWORD(v6) = v5;
  }
LABEL_4:
  *(_DWORD *)(a2 + 16) = v16;
  *(_DWORD *)(a2 + 20) = v5;
  v7 = v4 & 0xFFFFFFFFFFFF80F1LL;
  if ( (unsigned int)v6 <= 0x1F )
    v7 |= (_DWORD)v6 << 9;
  *v3 = v7;
  v3[1] = 0LL;
  *(_QWORD *)(a2 + 24) = v7;
  return 0;
}

//----- (000000000000089A) ----------------------------------------------------
char __fastcall AppleHPET::cpuDriverPublished(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v4; // r14@1
  __int64 v5; // r12@1
  __int64 v6; // rax@1
  int v7; // eax@1
  int v8; // eax@3
  char result; // al@11
  int v10; // [sp+8h] [bp-98h]@0
  __int64 v11; // [sp+10h] [bp-90h]@1
  __int64 v12; // [sp+18h] [bp-88h]@1
  __int64 v13; // [sp+20h] [bp-80h]@1
  int v14; // [sp+28h] [bp-78h]@1
  int v15; // [sp+2Ch] [bp-74h]@1
  char v16; // [sp+30h] [bp-70h]@5
  __int64 (__fastcall *v17)(AppleHPET *, int, void (*)(void), unsigned int *, unsigned int *, void **); // [sp+40h] [bp-60h]@3
  int (__fastcall *v18)(AppleHPET *, int); // [sp+48h] [bp-58h]@3
  __int64 (__fastcall *v19)(AppleHPET *, unsigned int, int); // [sp+50h] [bp-50h]@3
  __int64 (__fastcall *v20)(AppleHPET *__hidden); // [sp+58h] [bp-48h]@3
  __int64 (__fastcall *v21)(AppleHPET *__hidden); // [sp+60h] [bp-40h]@3
  char v22; // [sp+6Eh] [bp-32h]@3
  __int64 v23; // [sp+78h] [bp-28h]@1

  v4 = a4;
  v5 = qword_14A0;
  v23 = *(_QWORD *)qword_14A0;
  v11 = a1;
  v6 = *(_QWORD *)(a1 + 192);
  v12 = v6 + 240;
  v13 = v6 + 16;
  v14 = *(_DWORD *)(a1 + 216);
  v7 = *(_DWORD *)(a1 + 212);
  v15 = *(_DWORD *)(a1 + 212);
  if ( *(_BYTE *)(a1 + 240) )
    v15 = v7 - 1;
  v17 = AppleHPET::hpetTimerAcquire;
  v18 = AppleHPET::hpetTimerRelease;
  v19 = AppleHPET::hpetTimerCommand;
  v20 = AppleHPET::hpetSaveState;
  v21 = AppleHPET::hpetRestoreState;
  v8 = (*(int (__fastcall **)(__int64 (__fastcall *)(AppleHPET *__hidden), char *, signed __int64))(*(_QWORD *)AppleHPET::hpetRestoreState
                                                                                                  + 2232LL))(
         AppleHPET::hpetRestoreState,
         &v22,
         10LL);
  if ( !v8 || !v8 )
    v16 |= 1u;
  if ( !v8 && v10 == 261 && v4 )
    (*(void (__fastcall **)(__int64, __int64 *))(*(_QWORD *)v4 + 288LL))(v4, &v11);
  if ( *(_QWORD *)v5 == v23 )
    result = 1;
  else
    result = AppleHPET::stop();
  return result;
}
// 14A0: using guessed type __int64 qword_14A0;

//----- (0000000000000A92) ----------------------------------------------------
int AppleHPET::stop()
{
  return (*(int (**)(void))(qword_1498 + 1496))();
}
// 1498: using guessed type __int64 qword_1498;

//----- (0000000000000AA4) ----------------------------------------------------
void __fastcall AppleHPET::free(AppleHPET *this)
{
  AppleHPET *v1; // rbx@1
  __int64 v2; // rdi@1
  __int64 v3; // rdi@3
  __int64 v4; // rdi@5
  __int64 v5; // rdi@7
  __int64 v6; // rdi@11
  __int64 v7; // rax@11

  v1 = this;
  v2 = *((_QWORD *)this + 23);
  if ( v2 )
  {
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v2 + 280LL))(v2);
    *((_QWORD *)v1 + 23) = 0LL;
  }
  v3 = *((_QWORD *)v1 + 18);
  if ( v3 )
  {
    *((_QWORD *)v1 + 24) = 0LL;
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v3 + 40LL))(v3);
    *((_QWORD *)v1 + 18) = 0LL;
  }
  v4 = *((_QWORD *)v1 + 19);
  if ( v4 )
  {
    *((_QWORD *)v1 + 20) = 0LL;
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v4 + 40LL))(v4);
    *((_QWORD *)v1 + 19) = 0LL;
  }
  v5 = *((_QWORD *)v1 + 21);
  if ( v5 )
  {
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v5 + 40LL))(v5);
    *((_QWORD *)v1 + 21) = 0LL;
  }
  if ( *((_QWORD *)v1 + 25) && *((_DWORD *)v1 + 53) )
  {
    v6 = *((_QWORD *)v1 + 25);
    v7 = *((_DWORD *)v1 + 53);
    *((_QWORD *)v1 + 25) = 0LL;
  }
  if ( *((_QWORD *)v1 + 22) )
    *((_QWORD *)v1 + 22) = 0LL;
  JUMPOUT(__CS__, *(_QWORD *)(qword_1498 + 160));
}
// 1498: using guessed type __int64 qword_1498;

//----- (0000000000000BB8) ----------------------------------------------------
__int64 __fastcall AppleHPET::hpetTimerAcquire(AppleHPET *this, int a2, void (*a3)(void), unsigned int *a4, unsigned int *a5, void **a6)
{
  unsigned int *v6; // r13@1
  void (*v7)(void); // r12@1
  AppleHPET *v8; // rbx@1
  bool v9; // cl@1
  signed int v10; // er14@1
  __int64 v11; // rdi@3
  unsigned int v12; // eax@3
  unsigned int v13; // ecx@4
  __int64 v14; // r13@4
  __int64 v15; // r15@7
  __int64 v16; // rdi@15
  __int64 v18; // [sp+8h] [bp-48h]@12
  unsigned int *v19; // [sp+10h] [bp-40h]@4
  void **v20; // [sp+18h] [bp-38h]@4
  unsigned int *v21; // [sp+20h] [bp-30h]@3

  v6 = a4;
  v7 = a3;
  v8 = this;
  v9 = a4 == 0LL;
  v10 = -1;
  if ( a2 != -1 && a6 != 0LL && a5 != 0LL && !v9 && a3 != 0LL )
  {
    v21 = a5;
    v11 = *((_QWORD *)this + 22);
    v12 = *((_DWORD *)v8 + 53);
    if ( !v12 )
      goto LABEL_14;
    v19 = v6;
    v20 = a6;
    v13 = 0;
    v14 = 0LL;
    while ( 1 )
    {
      if ( v13 || !*((_BYTE *)v8 + 240) )
      {
        v15 = *((_QWORD *)v8 + 25);
        if ( *(_DWORD *)(v15 + v14 + 12) == -1 && *(_DWORD *)(v15 + v14 + 16) != -1 )
          break;
      }
      v14 += 40LL;
      ++v13;
      if ( v13 >= v12 )
        goto LABEL_14;
    }
    if ( v14 + v15
      && (v18 = v14 + v15, !AppleHPET::setInterruptMessageDestination(v8, v14 + v15, (unsigned int)a2))
      && !(*(int (__fastcall **)(_QWORD, _QWORD, AppleHPET *, void (*)(void), _QWORD))(**((_QWORD **)v8 + 17) + 1784LL))(
            *((_QWORD *)v8 + 17),
            *(_DWORD *)(v18 + 16),
            v8,
            v7,
            0LL) )
    {
      v10 = -1;
      if ( (*(int (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)v8 + 17) + 1808LL))(
             *((_QWORD *)v8 + 17),
             *(_DWORD *)(v18 + 16)) )
      {
        (*(void (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)v8 + 17) + 1792LL))(
          *((_QWORD *)v8 + 17),
          *(_DWORD *)(v18 + 16));
      }
      else
      {
        *(_DWORD *)(v15 + v14 + 12) = a2;
        *v21 = ((unsigned int)**(_QWORD **)(v15 + v14) >> 5) & 1;
        *v19 = *(_DWORD *)(v15 + v14 + 8);
        *v20 = (void *)(*(_QWORD *)(v15 + v14) + 8LL);
        v10 = 0;
      }
    }
    else
    {
LABEL_14:
      v10 = -1;
    }
    v16 = *((_QWORD *)v8 + 22);
  }
  return (unsigned int)v10;
}

//----- (0000000000000D48) ----------------------------------------------------
int __fastcall AppleHPET::hpetTimerRelease(AppleHPET *this, int a2)
{
  AppleHPET *v2; // r14@1
  __int64 v3; // rdi@2
  int result; // eax@2
  __int64 v5; // r15@2
  unsigned __int64 v6; // rax@3
  __int64 v7; // rdi@4

  v2 = this;
  if ( *((_DWORD *)this + 53) > (unsigned int)a2 )
  {
    v3 = *((_QWORD *)this + 22);
    result = a2;
    v5 = *((_QWORD *)v2 + 25);
    if ( *(_DWORD *)(v5 + 40LL * (unsigned int)a2 + 12) != -1 )
    {
      v6 = *(_QWORD *)(v5 + 40LL * (unsigned int)a2 + 24) & 0xFFFFFFFFFFFFFFFBLL;
      *(_QWORD *)(v5 + 40LL * (unsigned int)a2 + 24) = v6;
      **(_QWORD **)(v5 + 40LL * (unsigned int)a2) = v6;
      (*(void (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)v2 + 17) + 1816LL))(
        *((_QWORD *)v2 + 17),
        *(_DWORD *)(v5 + 40LL * (unsigned int)a2 + 16));
      result = (*(int (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)v2 + 17) + 1792LL))(
                 *((_QWORD *)v2 + 17),
                 *(_DWORD *)(v5 + 40LL * (unsigned int)a2 + 16));
      *(_DWORD *)(v5 + 40LL * (unsigned int)a2 + 12) = -1;
    }
    v7 = *((_QWORD *)v2 + 22);
  }
  return result;
}

//----- (0000000000000DF0) ----------------------------------------------------
__int64 __fastcall AppleHPET::hpetTimerCommand(AppleHPET *this, unsigned int a2, int a3)
{
  __int64 result; // rax@1
  __int64 v4; // r8@2
  signed __int64 v5; // r10@3
  unsigned __int64 v6; // rax@4

  result = 0xFFFFFFFFLL;
  if ( *((_DWORD *)this + 53) > a2 )
  {
    v4 = *((_QWORD *)this + 25);
    result = 4294967294LL;
    if ( *(_DWORD *)(v4 + 40LL * a2 + 12) != -1 )
    {
      v5 = v4 + 40LL * a2;
      if ( a3 )
      {
        result = 4294967293LL;
        if ( a3 != 1 )
          return result;
        *(_QWORD *)(*((_QWORD *)this + 24) + 32LL) = 1 << a2;
        *(_BYTE *)(v4 + 40LL * a2 + 24) |= 4u;
        *(_QWORD *)(*(_QWORD *)v5 + 8LL) = 0LL;
        v6 = *(_QWORD *)(v4 + 40LL * a2 + 24);
      }
      else
      {
        v6 = *(_QWORD *)(v4 + 40LL * a2 + 24) & 0xFFFFFFFFFFFFFFFBLL;
        *(_QWORD *)(v4 + 40LL * a2 + 24) = v6;
      }
      **(_QWORD **)v5 = v6;
      result = 0LL;
    }
  }
  return result;
}

//----- (0000000000000E74) ----------------------------------------------------
__int64 __fastcall AppleHPET::hpetSaveState(AppleHPET *this)
{
  unsigned int v1; // er8@1
  signed __int64 v2; // rdx@2
  signed __int64 v3; // rcx@2
  unsigned int v4; // esi@2
  __int64 result; // rax@4

  v1 = *((_DWORD *)this + 53);
  if ( v1 )
  {
    v2 = *((_QWORD *)this + 24) + 264LL;
    v3 = *((_QWORD *)this + 25) + 32LL;
    v4 = 0;
    do
    {
      *(_QWORD *)v3 = *(_QWORD *)v2;
      v2 += 32LL;
      v3 += 40LL;
      ++v4;
    }
    while ( v4 < v1 );
  }
  *((_QWORD *)this + 29) = *(_QWORD *)(*((_QWORD *)this + 24) + 240LL);
  result = *(_QWORD *)(*((_QWORD *)this + 24) + 16LL);
  *((_QWORD *)this + 28) = result;
  return result;
}

//----- (0000000000000EDC) ----------------------------------------------------
__int64 __fastcall AppleHPET::hpetRestoreState(AppleHPET *this)
{
  __int64 v1; // rax@1
  __int64 v2; // rax@3
  unsigned int v3; // eax@6
  signed __int64 v4; // rcx@7
  signed __int64 v5; // rdx@7
  unsigned int v6; // esi@7
  __int64 result; // rax@9

  v1 = *((_QWORD *)this + 24);
  if ( !*(_QWORD *)v1 || *(_QWORD *)v1 == -1LL )
  {
    v2 = *((_QWORD *)this + 20);
    if ( !(*(_DWORD *)v2 & 0x80) )
      *(_DWORD *)v2 = *(_DWORD *)v2 & 0xFFFFFF7C | 0x80;
    **((_DWORD **)this + 20);
    (*(void (__fastcall **)(_QWORD, signed __int64))(**((_QWORD **)this + 21) + 344LL))(*((_QWORD *)this + 21), 1LL);
  }
  *(_QWORD *)(*((_QWORD *)this + 24) + 16LL) = *((_QWORD *)this + 28);
  v3 = *((_DWORD *)this + 53);
  if ( v3 )
  {
    v4 = *((_QWORD *)this + 25) + 32LL;
    v5 = *((_QWORD *)this + 24) + 264LL;
    v6 = 0;
    do
    {
      *(_QWORD *)(v5 - 8) = *(_QWORD *)(v4 - 8);
      *(_QWORD *)v5 = *(_QWORD *)v4;
      v4 += 40LL;
      v5 += 32LL;
      ++v6;
    }
    while ( v6 < v3 );
  }
  *(_QWORD *)(*((_QWORD *)this + 24) + 32LL) = 0xFFFFFFFFLL;
  result = *((_QWORD *)this + 24);
  *(_QWORD *)(result + 240) = *((_QWORD *)this + 29);
  return result;
}

//----- (0000000000000FD0) ----------------------------------------------------
int __fastcall AppleHPET::setInterruptMessageDestination(AppleHPET *a1, __int64 a2, __int64 a3)
{
  unsigned int v3; // er14@1
  __int64 v4; // rbx@1
  __int64 v5; // rax@1
  int result; // eax@3

  v3 = a3;
  v4 = *(_DWORD *)(a2 + 20);
  LODWORD(v5) = AppleHPET::getInterruptControllerAtIndex(a1, *(_DWORD *)(a2 + 16), a3);
  if ( v4 && v5 )
    result = (*(int (__fastcall **)(__int64, _QWORD, _QWORD, __int64, _QWORD, _QWORD))(*(_QWORD *)v5 + 1728LL))(
               v5,
               "SetVectorPhysicalDestination",
               0LL,
               v4,
               v3,
               0LL);
  else
    result = -536870199;
  return result;
}

//----- (000000000000102C) ----------------------------------------------------
__int64 __fastcall AppleHPET::getInterruptVectorAtIndex(AppleHPET *this, unsigned int a2, __int64 a3)
{
  __int64 v3; // rax@1
  __int64 v4; // rbx@1
  signed int v5; // er15@1
  __int64 v6; // rdx@2
  __int64 v7; // rax@3
  __int64 v8; // rbx@3
  signed int *v9; // rax@5

  LODWORD(v3) = (*(int (__fastcall **)(_QWORD, _QWORD, __int64))(**((_QWORD **)this + 17) + 680LL))(
                  *((_QWORD *)this + 17),
                  *(_QWORD *)qword_14B8,
                  a3);
  v4 = v3;
  v5 = -1;
  if ( v3 )
  {
    if ( (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v3 + 304LL))(v3, *(_QWORD *)qword_1480) )
    {
      LODWORD(v7) = (*(int (__fastcall **)(__int64, _QWORD, __int64))(*(_QWORD *)v4 + 488LL))(v4, a2, v6);
      v8 = v7;
      if ( v7 )
      {
        if ( (unsigned int)(*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v7 + 320LL))(v7, *(_QWORD *)qword_1478) >= 4 )
        {
          LODWORD(v9) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v8 + 376LL))(v8);
          v5 = *v9;
        }
      }
    }
  }
  return (unsigned int)v5;
}
// 1478: using guessed type __int64 qword_1478;
// 1480: using guessed type __int64 qword_1480;
// 14B8: using guessed type __int64 qword_14B8;

//----- (00000000000010DA) ----------------------------------------------------
int __fastcall AppleHPET::getInterruptControllerAtIndex(AppleHPET *this, unsigned int a2, __int64 a3)
{
  __int64 v3; // rax@1
  __int64 v4; // rbx@1
  int result; // eax@1
  __int64 v6; // rdx@2
  int v7; // ecx@2
  __int64 v8; // rax@3
  __int64 v9; // rdx@3
  __int64 v10; // rsi@3
  __int64 v11; // rbx@3

  LODWORD(v3) = (*(int (__fastcall **)(_QWORD, _QWORD, __int64))(**((_QWORD **)this + 17) + 680LL))(
                  *((_QWORD *)this + 17),
                  *(_QWORD *)qword_14B0,
                  a3);
  v4 = v3;
  result = 0;
  if ( v4 )
  {
    v7 = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v4 + 304LL))(v4, *(_QWORD *)qword_1480);
    result = 0;
    if ( v7 )
    {
      LODWORD(v8) = (*(int (__fastcall **)(__int64, _QWORD, __int64))(*(_QWORD *)v4 + 488LL))(v4, a2, v6);
      v10 = *(_QWORD *)qword_1488;
      v11 = v8;
      result = 0;
      if ( v11 )
        result = (*(int (__fastcall **)(_QWORD, __int64, __int64))(*(_QWORD *)AppleHPET::MetaClass::MetaClass + 2312LL))(
                   0LL,
                   v11,
                   v9);
    }
  }
  return result;
}
// 1480: using guessed type __int64 qword_1480;
// 1488: using guessed type __int64 qword_1488;
// 14B0: using guessed type __int64 qword_14B0;

//----- (00000000000011D1) ----------------------------------------------------
int start()
{
  int result; // eax@2

  if ( v1F38 )
    result = v1F38();
  else
    result = 0;
  return result;
}
// 1F38: using guessed type int (*)(void);

//----- (00000000000011EB) ----------------------------------------------------
char *OSKextGetCurrentIdentifier()
{
  return &aCom_apple_driv[16];
}

//----- (00000000000011FC) ----------------------------------------------------
char *OSKextGetCurrentVersionString()
{
  return &aCom_apple_driv[80];
}

//----- (000000000000120D) ----------------------------------------------------
__int64 OSKextGetCurrentLoadTag()
{
  return *(_DWORD *)&aCom_apple_driv[12];
}

//----- (000000000000121D) ----------------------------------------------------
int stop()
{
  int result; // eax@2

  if ( v1F40 )
    result = v1F40();
  else
    result = 0;
  return result;
}
// 1F40: using guessed type int (*)(void);

// ALL OK, 30 function(s) have been successfully decompiled
